#!/usr/bin/env bash
#Script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then 
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"; 
else scp -o StrictHostKeyChecking=no -i "$4" "$2" "$9@$1":~/; 
fi;
